### ISSUE TITLE
springboot整合websocket - 昨日已逝去博客

### ISSUE THREAD

**Issue by DespairYoke** [DespairYoke/blog-comments#5]
http://zwd.ccxst.cn/springboot/2018/12/19/spring-websocket.html 

 <h3 id="websocket和http的区别">WebSocket和http的区别？</h3>
<ul>
  <li>
    <ol>
      <li>http协议是用在应用层的协议，他是基于tcp协议的，http协议建立链接也必须要有三次握手才能发送信息。</li>
    </ol>
  </li>
</ul>

**Comment by hansn007** [comment]
大神牛逼

**Comment by hansn007** [comment]
大神牛逼（此条一元）

**Comment by fire-basketball** [comment]
碉堡了

**Comment by DespairYoke** [comment]
> @hansn007
> 大神牛逼（此条一元）

傻掉
